import { useEffect, useState } from "react";
import axios from "axios";
import { useTranslation } from "react-i18next";
import { catalogApi, type AttributeType, type Category, type CategoryAttribute, type CategoryInput } from "../api/catalog";

const types: AttributeType[] = ["text", "number", "single_select", "multi_select", "boolean"];
const blank = (): CategoryAttribute => ({ key: "", label: "", type: "text", required: false, options: [], sort_order: 0 });

export default function CategoriesPage() {
  const { t } = useTranslation();
  const [items, setItems] = useState<Category[]>([]); const [editing, setEditing] = useState<Category | null | undefined>();
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [attributes, setAttributes] = useState<CategoryAttribute[]>([]); const [error, setError] = useState("");
  const load = () => { void catalogApi.listCategories().then(setItems).catch(() => setError(t("catalog.errors.load"))); };
  useEffect(() => { load(); }, []);
  const open = (category?: Category) => { setEditing(category ?? null); setName(category?.name ?? ""); setDescription(category?.description ?? ""); setAttributes(category?.attributes.map(a => ({ ...a, options: [...a.options] })) ?? []); };
  const updateRow = (index: number, patch: Partial<CategoryAttribute>) => setAttributes(rows => rows.map((row, i) => i === index ? { ...row, ...patch } : row));
  const move = (index: number, delta: number) => setAttributes(rows => { const next = [...rows]; const target = index + delta; if (target < 0 || target >= next.length) return rows; [next[index], next[target]] = [next[target], next[index]]; return next; });
  const message = (cause: unknown) => { if (axios.isAxiosError(cause)) { if (cause.response?.status === 409) return t("catalog.errors.conflict"); const detail = cause.response?.data?.detail; if (typeof detail === "string") return detail; if (detail && typeof detail === "object") return Object.values(detail).join(", "); } return t("catalog.errors.save"); };
  const save = async () => { const input: CategoryInput = { name, description: description || null, template_version: editing?.template_version, attributes: attributes.map(({ id: _id, ...a }, i) => ({ ...a, sort_order: i })) }; try { const saved = editing ? await catalogApi.updateCategory(editing.id, input) : await catalogApi.createCategory(input); setItems(old => editing ? old.map(x => x.id === saved.id ? saved : x) : [...old, saved]); setEditing(undefined); } catch (cause) { setError(message(cause)); } };
  const remove = async (item: Category) => { try { await catalogApi.deleteCategory(item.id); load(); } catch (cause) { setError(message(cause)); } };
  return <section className="categories-page"><div className="justify-between flex"><div><h1>{t("catalog.title")}</h1><p className="text-secondary">{t("catalog.subtitle")}</p></div><button className="btn btn-primary" onClick={() => open()}>{t("catalog.new")}</button></div>{error && <p role="alert" className="text-danger">{error}</p>}
    <div className="category-grid">{items.map(item => <article className="card category-card" key={item.id}><h2>{item.name}</h2><p>{item.description}</p><button className="btn btn-ghost" onClick={() => open(item)}>{t("catalog.edit")}</button><button className="btn btn-ghost" disabled={Boolean(item.product_count)} onClick={() => void remove(item)}>{t("catalog.delete")}</button>{Boolean(item.product_count) && <small>{t("catalog.products", { count: item.product_count })}</small>}</article>)}</div>
    {editing !== undefined && <div className="card category-editor"><label>{t("catalog.name")}<input value={name} onChange={e => setName(e.target.value)} /></label><label>{t("catalog.description")}<textarea value={description} onChange={e => setDescription(e.target.value)} /></label>{attributes.map((row, i) => <div className="attribute-row" key={i}><input aria-label={t("catalog.key")} value={row.key} onChange={e => updateRow(i, { key: e.target.value })}/><input aria-label={t("catalog.label")} value={row.label} onChange={e => updateRow(i, { label: e.target.value })}/><label>{t("catalog.type")}<select aria-label={t("catalog.type")} value={row.type} onChange={e => updateRow(i, { type: e.target.value as AttributeType, options: [] })}>{types.map(type => <option key={type}>{type}</option>)}</select></label>{row.type.includes("select") && <label>{t("catalog.options")}<input aria-label={t("catalog.options")} value={row.options.join(", ")} onChange={e => updateRow(i, { options: e.target.value.split(",").map(x => x.trim()).filter(Boolean) })}/></label>}<label>{t("catalog.required")}<input type="checkbox" checked={row.required} onChange={e => updateRow(i, { required: e.target.checked })}/></label><button aria-label={t("catalog.up")} onClick={() => move(i, -1)}>↑</button><button aria-label={t("catalog.down")} onClick={() => move(i, 1)}>↓</button><button aria-label={t("catalog.remove")} onClick={() => setAttributes(rows => rows.filter((_, index) => index !== i))}>×</button></div>)}<button className="btn" onClick={() => setAttributes(rows => [...rows, { ...blank(), sort_order: rows.length }])}>{t("catalog.addAttribute")}</button><button className="btn btn-primary" onClick={save}>{t("catalog.save")}</button></div>}
  </section>;
}
