import { useEffect, useState } from "react";
import { catalogApi, type AttributeType, type Category, type CategoryAttribute, type CategoryInput } from "../api/catalog";

const types: AttributeType[] = ["text", "number", "single_select", "multi_select", "boolean"];
const blank = (): CategoryAttribute => ({ key: "", label: "", type: "text", required: false, options: [], sort_order: 0 });

export default function CategoriesPage() {
  const [items, setItems] = useState<Category[]>([]); const [editing, setEditing] = useState<Category | null | undefined>();
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [attributes, setAttributes] = useState<CategoryAttribute[]>([]); const [error, setError] = useState("");
  const load = () => { void catalogApi.listCategories().then(setItems).catch(() => setError("Unable to load categories")); };
  useEffect(() => { load(); }, []);
  const open = (category?: Category) => { setEditing(category ?? null); setName(category?.name ?? ""); setDescription(category?.description ?? ""); setAttributes(category?.attributes.map(a => ({ ...a, options: [...a.options] })) ?? []); };
  const updateRow = (index: number, patch: Partial<CategoryAttribute>) => setAttributes(rows => rows.map((row, i) => i === index ? { ...row, ...patch } : row));
  const move = (index: number, delta: number) => setAttributes(rows => { const next = [...rows]; const target = index + delta; if (target < 0 || target >= next.length) return rows; [next[index], next[target]] = [next[target], next[index]]; return next; });
  const save = async () => { const input: CategoryInput = { name, description: description || null, template_version: editing?.template_version, attributes: attributes.map((a, i) => ({ ...a, sort_order: i })) }; try { const saved = editing ? await catalogApi.updateCategory(editing.id, input) : await catalogApi.createCategory(input); setItems(old => editing ? old.map(x => x.id === saved.id ? saved : x) : [...old, saved]); setEditing(undefined); } catch { setError("Could not save category. Refresh if the template changed."); } };
  return <section className="categories-page"><div className="justify-between flex"><div><h1>Categories</h1><p className="text-secondary">Manage reusable product attribute templates.</p></div><button className="btn btn-primary" onClick={() => open()}>New category</button></div>{error && <p className="text-danger">{error}</p>}
    <div className="category-grid">{items.map(item => <article className="card category-card" key={item.id}><h2>{item.name}</h2><p>{item.description}</p><button className="btn btn-ghost" onClick={() => open(item)}>Edit</button><button className="btn btn-ghost" disabled={Boolean(item.product_count)} onClick={() => catalogApi.deleteCategory(item.id).then(load)}>Delete</button>{Boolean(item.product_count) && <small>{item.product_count} products</small>}</article>)}</div>
    {editing !== undefined && <div className="card category-editor"><label>Name<input value={name} onChange={e => setName(e.target.value)} /></label><label>Description<textarea value={description} onChange={e => setDescription(e.target.value)} /></label>{attributes.map((row, i) => <div className="attribute-row" key={i}><input aria-label="Key" value={row.key} onChange={e => updateRow(i, { key: e.target.value })}/><input aria-label="Label" value={row.label} onChange={e => updateRow(i, { label: e.target.value })}/><label>Type<select aria-label="Type" value={row.type} onChange={e => updateRow(i, { type: e.target.value as AttributeType, options: [] })}>{types.map(type => <option key={type}>{type}</option>)}</select></label>{row.type.includes("select") && <label>Options<input aria-label="Options" value={row.options.join(", ")} onChange={e => updateRow(i, { options: e.target.value.split(",").map(x => x.trim()).filter(Boolean) })}/></label>}<button aria-label="Move up" onClick={() => move(i, -1)}>↑</button><button aria-label="Move down" onClick={() => move(i, 1)}>↓</button></div>)}<button className="btn" onClick={() => setAttributes(rows => [...rows, { ...blank(), sort_order: rows.length }])}>Add attribute</button><button className="btn btn-primary" onClick={save}>Save</button></div>}
  </section>;
}
