import { useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import { Link } from "react-router-dom";
import { catalogApi, type Category, type InitializationStatus, type Product } from "../api/catalog";
import MediaImage from "../components/MediaImage";

export default function ProductsPage() {
  const { t } = useTranslation(); const [items, setItems] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [initialization, setInitialization] = useState<InitializationStatus | null>(null); const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [error, setError] = useState("");
  const deletingRef = useRef(new Set<string>());
  const load = () => void catalogApi.listProducts({ ...(search ? { name: search } : {}), ...(category ? { category_id: category } : {}) }).then(result => setItems(result.items)).catch(() => setError(t("products.errors.load")));
  useEffect(() => { load(); void catalogApi.listCategories().then(setCategories); let timer: number | undefined; let disposed = false; const check = async () => { try { const status = await catalogApi.getInitializationStatus(); if (disposed) return; setInitialization(status); if (status.status === "pending") timer = window.setTimeout(() => void check(), 2000); } catch { if (disposed) return; setError(t("initialization.unavailable")); timer = window.setTimeout(() => void check(), 4000); } }; void check(); return () => { disposed = true; if (timer) window.clearTimeout(timer); }; }, []);
  const remove = async (product: Product) => { if (deletingRef.current.has(product.id)) return; if (product.task_count && !window.confirm(t("products.deleteWarning", { count: product.task_count }))) return; if (!window.confirm(t("products.deleteConfirm"))) return; deletingRef.current.add(product.id); try { await catalogApi.deleteProduct(product.id); load(); } catch { setError(t("products.errors.delete")); } finally { deletingRef.current.delete(product.id); } };
  return <section className="catalog-page">
    {initialization?.status === "pending" && <div className="notice notice-info"><span className="status-dot pulse" />{t("initialization.pending")}<Link to="/products/new">{t("initialization.manual")} →</Link></div>}
    {initialization?.status === "failed" && <div role="status" className="notice notice-error">{t("initialization.failed")}<Link to="/products/new">{t("initialization.manual")} →</Link></div>}
    <header className="workspace-header"><div><span className="eyebrow">{t("products.title").toUpperCase()}</span><h1>{t("products.title")}</h1><p className="text-secondary">{t("products.formIntro")}</p></div><Link className="btn btn-primary" to="/products/new"><span aria-hidden="true">＋</span> {t("products.new")}</Link></header>
    <div className="catalog-summary"><div><strong>{items.length}</strong><span>{t("products.title")}</span></div><div><strong>{categories.length}</strong><span>{t("catalog.title")}</span></div><div className="summary-note">{t("products.summary")}</div></div>
    {error && <p role="alert" className="notice notice-error">{error}</p>}
    <div className="filter-bar"><div className="search-field"><span aria-hidden="true">⌕</span><input aria-label={t("products.search")} placeholder={t("products.search")} value={search} onChange={event => setSearch(event.target.value)} onKeyDown={event => { if (event.key === "Enter") load(); }}/></div><select aria-label={t("products.category")} value={category} onChange={event => { setCategory(event.target.value); window.setTimeout(load, 0); }}><option value="">{t("products.allCategories")}</option>{categories.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><button className="btn" onClick={load}>{t("products.filter")}</button></div>
    {items.length === 0 ? <div className="card empty-state"><div className="empty-icon">＋</div><h2>{search || category ? t("products.emptyFiltered") : t("products.emptyTitle")}</h2><p>{search || category ? t("products.emptyFilteredDescription") : t("products.emptyDescription")}</p>{search || category ? <button className="btn" onClick={() => { setSearch(""); setCategory(""); window.setTimeout(load, 0); }}>{t("products.clearFilters")}</button> : <Link className="btn btn-primary" to="/products/new">{t("products.new")}</Link>}</div> :
      <div className="product-grid">{items.map(product => <article className="card product-card" key={product.id}><div className="product-visual">{product.main_image_asset_id ? <MediaImage assetId={product.main_image_asset_id} alt="" /> : <span aria-hidden="true">✦</span>}</div><div className="product-content"><div className="card-kicker">{product.category?.name || t("products.allCategories")}</div><h2>{product.name}</h2><p className="card-description">{product.description || "—"}</p><div className="chip-row">{product.selling_points.slice(0, 2).map(point => <span className="chip" key={point}>{point}</span>)}</div><div className="card-footer"><span className="metric">{t("products.tasks", { count: product.task_count ?? 0 })}</span><div className="card-actions"><Link className="btn btn-ghost" to={`/products/${product.id}/edit`}>{t("products.edit")}</Link><button className="btn btn-danger-ghost" onClick={() => void remove(product)}>{t("products.delete")}</button></div></div></div></article>)}</div>}
  </section>;
}
